import {
  Link,
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  useCatch,
} from '@remix-run/react';

import sharedStyles from '~/styles/shared.css';
import Error from './components/util/Error';

export const meta = () => ({
  charset: 'utf-8',
  title: 'New Remix App',
  viewport: 'width=device-width,initial-scale=1',
});

// Since <body> of App and the rest of the functions(CatchBoundary(), ErrorBoundary()) shares similar structure, we can create a function() for that structure and call it on those functions()
// This function() does not need to be export out so we can omit the word

// The differences for all of the functions will be their title and children(normal content or error content)
function Document({ title, children }) {
  return (
    <html lang="en">
      <head>
        <title>{title}</title>
        <Meta />
        <Links />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
    </html>
  );
}

export default function App() {
  return (
    <Document>
      <Outlet />
    </Document>
  );
}

export function CatchBoundary() {
  const caughtError = useCatch();
  return (
    <Document title={caughtError.statusText}>
      <main>
        <Error title={caughtError.statusText}>
          <p>
            {/* The Not Found text seen on the front-end is automatically generated by Remix */}
            {caughtError.data?.message ||
              'Something went wrong. Please try again later...'}
          </p>
          <p>
            Back to <Link to="/">safety</Link>.
          </p>
        </Error>
      </main>
    </Document>
  );
}

export function ErrorBoundary() {}

// This is still a route file therefore links() can be called and used
export function links() {
  return [{ rel: 'stylesheet', href: sharedStyles }];
}
